[package]
name = "pmt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.21", features = ["derive"]}
sysinfo = "0.32.0"
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros","full"] }
reqwest = "0.12.9"